# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SayKit SDK (Developer Preview)
email: engineering@conversantlabs.com
description: > # this means to ignore newlines until "baseurl:"
  The conversational UI framework for voice enabled applications on iOS.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://developer.conversantlabs.com" # the base hostname & protocol for your site
twitter_username: ConversantLabs
github_username:  ConversantLabs

# Build settings
exclude: ["README.md"]
markdown: redcarpet
# markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge
